-- Feature: Inventario de Volquetes (ABM + estados + historial)
-- Ticket: [T1] DB: tabla volquetes + estados + historial
-- Referencia: memory-bank/06-data-model.md
-- Sin Flyway/Liquibase. Ejecución manual.

-- Tabla volquetes: inventario por código interno/externo y estado actual
CREATE TABLE volquetes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo_interno   VARCHAR(50) NOT NULL,
    codigo_externo   VARCHAR(50) NOT NULL,
    estado_actual    VARCHAR(20) NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT pk_volquetes PRIMARY KEY (id),
    CONSTRAINT uk_volquetes_codigo_interno UNIQUE (codigo_interno),
    CONSTRAINT uk_volquetes_codigo_externo UNIQUE (codigo_externo),
    CONSTRAINT chk_volquetes_estado_actual CHECK (
        estado_actual IN ('DISPONIBLE', 'EN_CLIENTE', 'EN_TRANSITO', 'FUERA_DE_SERVICIO')
    )
);

COMMENT ON TABLE volquetes IS 'Inventario de volquetes. Estados: DISPONIBLE, EN_CLIENTE, EN_TRANSITO, FUERA_DE_SERVICIO. T1 Inventario Volquetes.';

CREATE INDEX idx_volquetes_estado_actual ON volquetes (estado_actual);

-- Tabla historial de cambios de estado (una fila por transición)
CREATE TABLE volquete_estado_historial (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    volquete_id  BIGINT NOT NULL,
    estado_desde  VARCHAR(20) NOT NULL,
    estado_hasta  VARCHAR(20) NOT NULL,
    fecha_hora   TIMESTAMPTZ NOT NULL DEFAULT now(),
    origen       VARCHAR(10),
    CONSTRAINT pk_volquete_estado_historial PRIMARY KEY (id),
    CONSTRAINT fk_volquete_historial_volquete FOREIGN KEY (volquete_id)
        REFERENCES volquetes (id) ON DELETE RESTRICT,
    CONSTRAINT chk_volquete_historial_estado_desde CHECK (
        estado_desde IN ('DISPONIBLE', 'EN_CLIENTE', 'EN_TRANSITO', 'FUERA_DE_SERVICIO')
    ),
    CONSTRAINT chk_volquete_historial_estado_hasta CHECK (
        estado_hasta IN ('DISPONIBLE', 'EN_CLIENTE', 'EN_TRANSITO', 'FUERA_DE_SERVICIO')
    ),
    CONSTRAINT chk_volquete_historial_origen CHECK (
        origen IS NULL OR origen IN ('MANUAL', 'PEDIDO')
    )
);

COMMENT ON TABLE volquete_estado_historial IS 'Historial de cambios de estado por volquete. Origen: MANUAL | PEDIDO (opcional). T1 Inventario Volquetes.';

CREATE INDEX idx_volquete_estado_historial_volquete_id ON volquete_estado_historial (volquete_id);
