-- Feature: Gestión de Pedidos (Issue 3)
-- Ticket: T1 — DB: tablas pedidos, choferes, camiones + constraints
-- Referencia: memory-bank/06-data-model.md
-- Sin Flyway/Liquibase. Ejecución manual.
-- Orden: choferes, camiones, pedidos (pedidos tiene FK a las tres tablas existentes + choferes/camiones).

-- Tabla choferes: catálogo mínimo para asignación (estado ASIGNADO)
CREATE TABLE choferes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT pk_choferes PRIMARY KEY (id)
);

COMMENT ON TABLE choferes IS 'Catálogo choferes para asignación de pedidos. T1 Issue 3 Pedidos.';

-- Tabla camiones: catálogo mínimo para asignación (estado ASIGNADO)
CREATE TABLE camiones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    patente     VARCHAR(20) NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT pk_camiones PRIMARY KEY (id)
);

COMMENT ON TABLE camiones IS 'Catálogo camiones para asignación de pedidos. T1 Issue 3 Pedidos.';

-- Tabla pedidos: cliente, volquete, dirección de entrega, estado, fechas, asignación chofer/camión
CREATE TABLE pedidos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id              BIGINT NOT NULL,
    volquete_id             BIGINT NOT NULL,
    direccion_entrega       VARCHAR(500) NOT NULL,
    estado                  VARCHAR(20) NOT NULL,
    fecha_creacion          TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_entrega_prevista  TIMESTAMPTZ,
    fecha_entrega_real      TIMESTAMPTZ,
    fecha_retiro_real       TIMESTAMPTZ,
    chofer_id               BIGINT,
    camion_id               BIGINT,
    created_at              TIMESTAMPTZ DEFAULT now(),
    updated_at              TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT pk_pedidos PRIMARY KEY (id),
    CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_pedidos_volquete FOREIGN KEY (volquete_id)
        REFERENCES volquetes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_pedidos_chofer FOREIGN KEY (chofer_id)
        REFERENCES choferes (id) ON DELETE SET NULL,
    CONSTRAINT fk_pedidos_camion FOREIGN KEY (camion_id)
        REFERENCES camiones (id) ON DELETE SET NULL,
    CONSTRAINT chk_pedidos_estado CHECK (
        estado IN ('NUEVO', 'ASIGNADO', 'ENTREGADO', 'RETIRADO', 'CERRADO', 'CANCELADO')
    )
);

COMMENT ON TABLE pedidos IS 'Pedidos de servicio. Un volquete solo puede estar en un pedido activo (NUEVO/ASIGNADO/ENTREGADO). T1 Issue 3.';

-- Índices para listados y filtros
CREATE INDEX idx_pedidos_estado ON pedidos (estado);
CREATE INDEX idx_pedidos_cliente_id ON pedidos (cliente_id);
CREATE INDEX idx_pedidos_volquete_id ON pedidos (volquete_id);

-- Unicidad: un volquete solo en un pedido activo (índice único parcial)
CREATE UNIQUE INDEX uk_pedidos_volquete_activo ON pedidos (volquete_id)
    WHERE estado IN ('NUEVO', 'ASIGNADO', 'ENTREGADO');
