-- Feature: Gestión de Clientes (ABM + tipo común/abono)
-- T1 — DB: Script incremental tabla clientes
-- Referencia: memory-bank/06-data-model.md
-- Sin Flyway/Liquibase. Ejecución manual.

CREATE TABLE clientes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    razon_social    VARCHAR(255) NOT NULL,
    telefono        VARCHAR(50),
    email           VARCHAR(255),
    direccion_principal VARCHAR(500),
    tipo            VARCHAR(10) NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT chk_clientes_tipo CHECK (tipo IN ('COMUN', 'ABONO'))
);

COMMENT ON TABLE clientes IS 'Clientes para asociar a pedidos. Tipo: COMUN | ABONO. Feature: Gestión de Clientes.';
COMMENT ON COLUMN clientes.razon_social IS 'Nombre o razón social (no vacío validado en app).';

CREATE INDEX idx_clientes_nombre ON clientes (razon_social);
